// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var calibreUpdate = CalibreUpdate.FromJson(jsonString);

namespace OpenDirectoryDownloader.Calibre.CalibreUpdate
{
	using System.Collections.Generic;
	using System.Globalization;
	using System.Text.Json;
	using System.Text.Json.Serialization;
	using OpenDirectoryDownloader.Converters;

	public partial class CalibreUpdate
	{
		[JsonPropertyName("icon_map")]
		public IconMap IconMap { get; set; }

		[JsonPropertyName("library_map")]
		public Dictionary<string, string> LibraryMap { get; set; }

		//[JsonPropertyName("translations")]
		//public bool Translations { get; set; }

		[JsonPropertyName("output_format")]
		public string OutputFormat { get; set; }

		[JsonPropertyName("custom_list_template")]
		public CustomListTemplate CustomListTemplate { get; set; }

		[JsonPropertyName("gui_last_modified_display_format")]
		public string GuiLastModifiedDisplayFormat { get; set; }

		[JsonPropertyName("icon_path")]
		public string IconPath { get; set; }

		[JsonPropertyName("completion_mode")]
		public string CompletionMode { get; set; }

		[JsonPropertyName("username")]
		public object Username { get; set; }

		[JsonPropertyName("default_library_id")]
		public string DefaultLibraryId { get; set; }

		[JsonPropertyName("input_formats")]
		public Dictionary<string, bool> InputFormats { get; set; }

		[JsonPropertyName("gui_pubdate_display_format")]
		public string GuiPubdateDisplayFormat { get; set; }

		[JsonPropertyName("gui_timestamp_display_format")]
		public string GuiTimestampDisplayFormat { get; set; }

		[JsonPropertyName("num_per_page")]
		public long NumPerPage { get; set; }

		[JsonPropertyName("use_roman_numerals_for_series_number")]
		public bool UseRomanNumeralsForSeriesNumber { get; set; }
	}

	public partial class CustomListTemplate
	{
		[JsonPropertyName("thumbnail_height")]
		public long ThumbnailHeight { get; set; }

		[JsonPropertyName("height")]
		public string Height { get; set; }

		[JsonPropertyName("comments_fields")]
		public string[] CommentsFields { get; set; }

		[JsonPropertyName("lines")]
		public string[] Lines { get; set; }

		[JsonPropertyName("thumbnail")]
		public bool Thumbnail { get; set; }
	}

	public partial class IconMap
	{
		[JsonPropertyName("gst")]
		public string Gst { get; set; }

		[JsonPropertyName("languages")]
		public string Languages { get; set; }

		[JsonPropertyName("formats")]
		public string Formats { get; set; }

		[JsonPropertyName("rating")]
		public string Rating { get; set; }

		[JsonPropertyName("news")]
		public string News { get; set; }

		[JsonPropertyName("series")]
		public string Series { get; set; }

		[JsonPropertyName("file_type_icons")]
		public FileTypeIcons FileTypeIcons { get; set; }

		[JsonPropertyName("user:")]
		public string User { get; set; }

		[JsonPropertyName("publisher")]
		public string Publisher { get; set; }

		[JsonPropertyName("custom:")]
		public string Custom { get; set; }

		[JsonPropertyName("authors")]
		public string Authors { get; set; }

		[JsonPropertyName("tags")]
		public string Tags { get; set; }

		[JsonPropertyName("search")]
		public string Search { get; set; }

		[JsonPropertyName("identifiers")]
		public string Identifiers { get; set; }
	}

	public partial class FileTypeIcons
	{
		[JsonPropertyName("epub")]
		public string Epub { get; set; }

		[JsonPropertyName("gif")]
		public string Gif { get; set; }

		[JsonPropertyName("dir")]
		public string Dir { get; set; }

		[JsonPropertyName("pdr")]
		public string Pdr { get; set; }

		[JsonPropertyName("mobi")]
		public string Mobi { get; set; }

		[JsonPropertyName("opml")]
		public string Opml { get; set; }

		[JsonPropertyName("fb2")]
		public string Fb2 { get; set; }

		[JsonPropertyName("azw")]
		public string Azw { get; set; }

		[JsonPropertyName("pdf")]
		public string Pdf { get; set; }

		[JsonPropertyName("xhtml")]
		public string Xhtml { get; set; }

		[JsonPropertyName("tpz")]
		public string Tpz { get; set; }

		[JsonPropertyName("htmlz")]
		public string Htmlz { get; set; }

		[JsonPropertyName("lit")]
		public string Lit { get; set; }

		[JsonPropertyName("lrx")]
		public string Lrx { get; set; }

		[JsonPropertyName("zero")]
		public string Zero { get; set; }

		[JsonPropertyName("bmp")]
		public string Bmp { get; set; }

		[JsonPropertyName("svg")]
		public string Svg { get; set; }

		[JsonPropertyName("lrf")]
		public string Lrf { get; set; }

		[JsonPropertyName("png")]
		public string Png { get; set; }

		[JsonPropertyName("rtf")]
		public string Rtf { get; set; }

		[JsonPropertyName("jpeg")]
		public string Jpeg { get; set; }

		[JsonPropertyName("azw2")]
		public string Azw2 { get; set; }

		[JsonPropertyName("zip")]
		public string Zip { get; set; }

		[JsonPropertyName("djv")]
		public string Djv { get; set; }

		[JsonPropertyName("default")]
		public string Default { get; set; }

		[JsonPropertyName("cbz")]
		public string Cbz { get; set; }

		[JsonPropertyName("xps")]
		public string Xps { get; set; }

		[JsonPropertyName("pobi")]
		public string Pobi { get; set; }

		[JsonPropertyName("text")]
		public string Text { get; set; }

		[JsonPropertyName("rar")]
		public string Rar { get; set; }

		[JsonPropertyName("jpg")]
		public string Jpg { get; set; }

		[JsonPropertyName("xhtm")]
		public string Xhtm { get; set; }

		[JsonPropertyName("html")]
		public string Html { get; set; }

		[JsonPropertyName("azw1")]
		public string Azw1 { get; set; }

		[JsonPropertyName("docx")]
		public string Docx { get; set; }

		[JsonPropertyName("azw3")]
		public string Azw3 { get; set; }

		[JsonPropertyName("azw4")]
		public string Azw4 { get; set; }

		[JsonPropertyName("cbr")]
		public string Cbr { get; set; }

		[JsonPropertyName("prc")]
		public string Prc { get; set; }

		[JsonPropertyName("snb")]
		public string Snb { get; set; }

		[JsonPropertyName("djvu")]
		public string Djvu { get; set; }

		[JsonPropertyName("tan")]
		public string Tan { get; set; }

		[JsonPropertyName("odt")]
		public string Odt { get; set; }

		[JsonPropertyName("mbp")]
		public string Mbp { get; set; }

		[JsonPropertyName("oxps")]
		public string Oxps { get; set; }

		[JsonPropertyName("htm")]
		public string Htm { get; set; }

		[JsonPropertyName("txt")]
		public string Txt { get; set; }
	}

	public partial class CalibreUpdate
	{
		public static CalibreUpdate FromJson(string json) => JsonSerializer.Deserialize<CalibreUpdate>(json, Converter.Settings);
	}

	public static class Serialize
	{
		public static string ToJson(this CalibreUpdate self) => JsonSerializer.Serialize(self, Converter.Settings);
	}

	internal static class Converter
	{
		public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
		{
			Converters =
			{
				new IsoDateTimeOffsetConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}
}
