// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var calibre = Calibre.FromJson(jsonString);

namespace OpenDirectoryDownloader.CalibreResult
{
	using System.Collections.Generic;
	using System.Globalization;
	using System.Text.Json;
	using System.Text.Json.Serialization;
	using OpenDirectoryDownloader.Converters;

	public partial class CalibreResult
	{
		[JsonPropertyName("metadata")]
		public Dictionary<string, Metadatum> Metadata { get; set; }

		[JsonPropertyName("book_display_fields")]
		public string[] BookDisplayFields { get; set; }

		[JsonPropertyName("library_id")]
		public string LibraryId { get; set; }

		[JsonPropertyName("sortable_fields")]
		public string[][] SortableFields { get; set; }

		[JsonPropertyName("field_metadata")]
		public FieldMetadata FieldMetadata { get; set; }

		[JsonPropertyName("virtual_libraries")]
		public Dictionary<string, string> VirtualLibraries { get; set; }

		[JsonPropertyName("search_result")]
		public SearchResult SearchResult { get; set; }
	}

	public partial class FieldMetadata
	{
		[JsonPropertyName("marked")]
		public Read Marked { get; set; }

		[JsonPropertyName("id")]
		public Read Id { get; set; }

		[JsonPropertyName("rating")]
		public Read Rating { get; set; }

		[JsonPropertyName("formats")]
		public Authors Formats { get; set; }

		[JsonPropertyName("authors")]
		public Authors Authors { get; set; }

		[JsonPropertyName("#read")]
		public Read Read { get; set; }

		[JsonPropertyName("series_sort")]
		public Read SeriesSort { get; set; }

		[JsonPropertyName("languages")]
		public Authors Languages { get; set; }

		[JsonPropertyName("cover")]
		public Read Cover { get; set; }

		[JsonPropertyName("last_modified")]
		public LastModified LastModified { get; set; }

		[JsonPropertyName("size")]
		public Read Size { get; set; }

		[JsonPropertyName("identifiers")]
		public Authors Identifiers { get; set; }

		[JsonPropertyName("sort")]
		public Read Sort { get; set; }

		[JsonPropertyName("series_index")]
		public Read SeriesIndex { get; set; }

		[JsonPropertyName("title")]
		public Read Title { get; set; }

		[JsonPropertyName("au_map")]
		public AuMap AuMap { get; set; }

		[JsonPropertyName("ondevice")]
		public Read Ondevice { get; set; }

		[JsonPropertyName("comments")]
		public Read Comments { get; set; }

		[JsonPropertyName("news")]
		public Read News { get; set; }

		[JsonPropertyName("series")]
		public Read Series { get; set; }

		[JsonPropertyName("uuid")]
		public Read Uuid { get; set; }

		[JsonPropertyName("tags")]
		public Authors Tags { get; set; }

		[JsonPropertyName("pubdate")]
		public LastModified Pubdate { get; set; }

		[JsonPropertyName("author_sort")]
		public Read AuthorSort { get; set; }

		[JsonPropertyName("path")]
		public Read Path { get; set; }

		[JsonPropertyName("publisher")]
		public Read Publisher { get; set; }

		[JsonPropertyName("timestamp")]
		public LastModified Timestamp { get; set; }
	}

	public partial class AuMap
	{
		[JsonPropertyName("column")]
		public object Column { get; set; }

		[JsonPropertyName("label")]
		public string Label { get; set; }

		[JsonPropertyName("datatype")]
		public string Datatype { get; set; }

		[JsonPropertyName("is_multiple")]
		public IsMultiple IsMultiple { get; set; }

		[JsonPropertyName("display")]
		public IsMultipleClass Display { get; set; }

		[JsonPropertyName("rec_index")]
		public long RecIndex { get; set; }

		[JsonPropertyName("is_csp")]
		public bool IsCsp { get; set; }

		[JsonPropertyName("is_category")]
		public bool IsCategory { get; set; }

		[JsonPropertyName("search_terms")]
		public object[] SearchTerms { get; set; }

		[JsonPropertyName("name")]
		public object Name { get; set; }

		[JsonPropertyName("is_editable")]
		public bool IsEditable { get; set; }

		[JsonPropertyName("is_custom")]
		public bool IsCustom { get; set; }

		[JsonPropertyName("table")]
		public object Table { get; set; }

		[JsonPropertyName("kind")]
		public Kind Kind { get; set; }
	}

	public partial class IsMultipleClass
	{
	}

	public partial class IsMultiple
	{
		[JsonPropertyName("cache_to_list")]
		public string CacheToList { get; set; }

		[JsonPropertyName("list_to_ui")]
		public string ListToUi { get; set; }

		[JsonPropertyName("ui_to_list")]
		public string UiToList { get; set; }
	}

	public partial class Read
	{
		[JsonPropertyName("column")]
		public string Column { get; set; }

		[JsonPropertyName("label")]
		public string Label { get; set; }

		[JsonPropertyName("is_category")]
		public bool IsCategory { get; set; }

		[JsonPropertyName("display")]
		public IsMultipleClass Display { get; set; }

		[JsonPropertyName("is_csp")]
		public bool IsCsp { get; set; }

		[JsonPropertyName("category_sort")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string CategorySort { get; set; }

		[JsonPropertyName("search_terms")]
		public string[] SearchTerms { get; set; }

		[JsonPropertyName("datatype")]
		public string Datatype { get; set; }

		[JsonPropertyName("name")]
		public string Name { get; set; }

		[JsonPropertyName("is_multiple")]
		public IsMultipleClass IsMultiple { get; set; }

		[JsonPropertyName("link_column")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string LinkColumn { get; set; }

		[JsonPropertyName("is_editable")]
		public bool IsEditable { get; set; }

		[JsonPropertyName("is_custom")]
		public bool IsCustom { get; set; }

		[JsonPropertyName("rec_index")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public long? RecIndex { get; set; }

		[JsonPropertyName("colnum")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public long? Colnum { get; set; }

		[JsonPropertyName("table")]
		public string Table { get; set; }

		[JsonPropertyName("kind")]
		public Kind Kind { get; set; }
	}

	public partial class Authors
	{
		[JsonPropertyName("column")]
		public string Column { get; set; }

		[JsonPropertyName("label")]
		public string Label { get; set; }

		[JsonPropertyName("datatype")]
		public string Datatype { get; set; }

		[JsonPropertyName("is_multiple")]
		public IsMultiple IsMultiple { get; set; }

		[JsonPropertyName("link_column")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string LinkColumn { get; set; }

		[JsonPropertyName("display")]
		public IsMultipleClass Display { get; set; }

		[JsonPropertyName("rec_index")]
		public long RecIndex { get; set; }

		[JsonPropertyName("is_csp")]
		public bool IsCsp { get; set; }

		[JsonPropertyName("is_category")]
		public bool IsCategory { get; set; }

		[JsonPropertyName("category_sort")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string CategorySort { get; set; }

		[JsonPropertyName("search_terms")]
		public string[] SearchTerms { get; set; }

		[JsonPropertyName("name")]
		public string Name { get; set; }

		[JsonPropertyName("is_editable")]
		public bool IsEditable { get; set; }

		[JsonPropertyName("is_custom")]
		public bool IsCustom { get; set; }

		[JsonPropertyName("table")]
		public string Table { get; set; }

		[JsonPropertyName("kind")]
		public Kind Kind { get; set; }
	}

	public partial class LastModified
	{
		[JsonPropertyName("column")]
		public object Column { get; set; }

		[JsonPropertyName("label")]
		public string Label { get; set; }

		[JsonPropertyName("datatype")]
		public string Datatype { get; set; }

		[JsonPropertyName("is_multiple")]
		public IsMultipleClass IsMultiple { get; set; }

		[JsonPropertyName("display")]
		public LastModifiedDisplay Display { get; set; }

		[JsonPropertyName("rec_index")]
		public long RecIndex { get; set; }

		[JsonPropertyName("is_csp")]
		public bool IsCsp { get; set; }

		[JsonPropertyName("is_category")]
		public bool IsCategory { get; set; }

		[JsonPropertyName("search_terms")]
		public string[] SearchTerms { get; set; }

		[JsonPropertyName("name")]
		public string Name { get; set; }

		[JsonPropertyName("is_editable")]
		public bool IsEditable { get; set; }

		[JsonPropertyName("is_custom")]
		public bool IsCustom { get; set; }

		[JsonPropertyName("table")]
		public object Table { get; set; }

		[JsonPropertyName("kind")]
		public Kind Kind { get; set; }
	}

	public partial class LastModifiedDisplay
	{
		[JsonPropertyName("date_format")]
		public string DateFormat { get; set; }
	}

	public partial class Metadatum
	{
		[JsonPropertyName("author_sort")]
		public string AuthorSort { get; set; }

		[JsonPropertyName("timestamp")]
		public DateTimeOffset Timestamp { get; set; }

		[JsonPropertyName("sort")]
		public string Sort { get; set; }

		[JsonPropertyName("series_index")]
		public long SeriesIndex { get; set; }

		[JsonPropertyName("format_sizes")]
		public Dictionary<string, long> FormatSizes { get; set; }

		[JsonPropertyName("formats")]
		public List<string> Formats { get; set; }

		[JsonPropertyName("title")]
		public string Title { get; set; }

		[JsonPropertyName("last_modified")]
		public DateTimeOffset LastModified { get; set; }

		[JsonPropertyName("uuid")]
		public Guid Uuid { get; set; }

		[JsonPropertyName("authors")]
		public string[] Authors { get; set; }

		[JsonPropertyName("comments")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string Comments { get; set; }

		[JsonPropertyName("publisher")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string Publisher { get; set; }

		[JsonPropertyName("lang_names")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public Dictionary<string, string> LangNames { get; set; }

		[JsonPropertyName("pubdate")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public DateTimeOffset? PublishDate { get; set; }

		[JsonPropertyName("languages")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public List<string> Languages { get; set; }

		[JsonPropertyName("identifiers")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public Dictionary<string, string> Identifiers { get; set; }

		[JsonPropertyName("urls_from_identifiers")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string[][] UrlsFromIdentifiers { get; set; }

		[JsonPropertyName("rating")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public long? Rating { get; set; }

		[JsonPropertyName("tags")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string[] Tags { get; set; }

		[JsonPropertyName("series")]
		[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
		public string Series { get; set; }
	}

	public partial class SearchResult
	{
		[JsonPropertyName("base_url")]
		public string BaseUrl { get; set; }

		[JsonPropertyName("book_ids")]
		public long[] BookIds { get; set; }

		[JsonPropertyName("offset")]
		public long Offset { get; set; }

		[JsonPropertyName("sort")]
		public string Sort { get; set; }

		[JsonPropertyName("sort_order")]
		public string SortOrder { get; set; }

		[JsonPropertyName("total_num")]
		public long TotalNum { get; set; }

		[JsonPropertyName("num")]
		public long Num { get; set; }

		[JsonPropertyName("library_id")]
		public string LibraryId { get; set; }

		[JsonPropertyName("vl")]
		public string Vl { get; set; }

		[JsonPropertyName("query")]
		public string Query { get; set; }
	}

	public enum Kind { Category, Field };

	public enum Format { Azw3, Epub, Imp, Mobi, Pdf, Rar, Zip };

	public partial class CalibreResult
	{
		public static CalibreResult FromJson(string json) => JsonSerializer.Deserialize<CalibreResult>(json, Converter.Settings);
	}

	public static class Serialize
	{
		public static string ToJson(this CalibreResult self) => JsonSerializer.Serialize(self, Converter.Settings);
	}

	internal static class Converter
	{
		public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
		{
			Converters =
			{
				KindConverter.Singleton,
				new IsoDateTimeOffsetConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}

	internal class KindConverter : JsonConverter<Kind>
	{
		public override Kind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
		{
			string value = reader.GetString();

			return value switch
			{
				"category" => Kind.Category,
				"field" => Kind.Field,
				_ => throw new JsonException("Cannot unmarshal type Kind")
			};
		}

		public override void Write(Utf8JsonWriter writer, Kind value, JsonSerializerOptions options)
		{
			switch (value)
			{
				case Kind.Category:
					writer.WriteStringValue("category");
					return;
				case Kind.Field:
					writer.WriteStringValue("field");
					return;
				default:
					throw new JsonException("Cannot marshal type Kind");
			}
		}

		public static readonly KindConverter Singleton = new();
	}
}
