// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var calibreUpdate = CalibreUpdate.FromJson(jsonString);

namespace OpenDirectoryDownloader.Calibre.CalibreUpdate
{
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CalibreUpdate
    {
        [JsonProperty("icon_map")]
        public IconMap IconMap { get; set; }

        [JsonProperty("library_map")]
        public Dictionary<string, string> LibraryMap { get; set; }

        //[JsonProperty("translations")]
        //public bool Translations { get; set; }

        [JsonProperty("output_format")]
        public string OutputFormat { get; set; }

        [JsonProperty("custom_list_template")]
        public CustomListTemplate CustomListTemplate { get; set; }

        [JsonProperty("gui_last_modified_display_format")]
        public string GuiLastModifiedDisplayFormat { get; set; }

        [JsonProperty("icon_path")]
        public string IconPath { get; set; }

        [JsonProperty("completion_mode")]
        public string CompletionMode { get; set; }

        [JsonProperty("username")]
        public object Username { get; set; }

        [JsonProperty("default_library_id")]
        public string DefaultLibraryId { get; set; }

        [JsonProperty("input_formats")]
        public Dictionary<string, bool> InputFormats { get; set; }

        [JsonProperty("gui_pubdate_display_format")]
        public string GuiPubdateDisplayFormat { get; set; }

        [JsonProperty("gui_timestamp_display_format")]
        public string GuiTimestampDisplayFormat { get; set; }

        [JsonProperty("num_per_page")]
        public long NumPerPage { get; set; }

        [JsonProperty("use_roman_numerals_for_series_number")]
        public bool UseRomanNumeralsForSeriesNumber { get; set; }
    }

    public partial class CustomListTemplate
    {
        [JsonProperty("thumbnail_height")]
        public long ThumbnailHeight { get; set; }

        [JsonProperty("height")]
        public string Height { get; set; }

        [JsonProperty("comments_fields")]
        public string[] CommentsFields { get; set; }

        [JsonProperty("lines")]
        public string[] Lines { get; set; }

        [JsonProperty("thumbnail")]
        public bool Thumbnail { get; set; }
    }

    public partial class IconMap
    {
        [JsonProperty("gst")]
        public string Gst { get; set; }

        [JsonProperty("languages")]
        public string Languages { get; set; }

        [JsonProperty("formats")]
        public string Formats { get; set; }

        [JsonProperty("rating")]
        public string Rating { get; set; }

        [JsonProperty("news")]
        public string News { get; set; }

        [JsonProperty("series")]
        public string Series { get; set; }

        [JsonProperty("file_type_icons")]
        public FileTypeIcons FileTypeIcons { get; set; }

        [JsonProperty("user:")]
        public string User { get; set; }

        [JsonProperty("publisher")]
        public string Publisher { get; set; }

        [JsonProperty("custom:")]
        public string Custom { get; set; }

        [JsonProperty("authors")]
        public string Authors { get; set; }

        [JsonProperty("tags")]
        public string Tags { get; set; }

        [JsonProperty("search")]
        public string Search { get; set; }

        [JsonProperty("identifiers")]
        public string Identifiers { get; set; }
    }

    public partial class FileTypeIcons
    {
        [JsonProperty("epub")]
        public string Epub { get; set; }

        [JsonProperty("gif")]
        public string Gif { get; set; }

        [JsonProperty("dir")]
        public string Dir { get; set; }

        [JsonProperty("pdr")]
        public string Pdr { get; set; }

        [JsonProperty("mobi")]
        public string Mobi { get; set; }

        [JsonProperty("opml")]
        public string Opml { get; set; }

        [JsonProperty("fb2")]
        public string Fb2 { get; set; }

        [JsonProperty("azw")]
        public string Azw { get; set; }

        [JsonProperty("pdf")]
        public string Pdf { get; set; }

        [JsonProperty("xhtml")]
        public string Xhtml { get; set; }

        [JsonProperty("tpz")]
        public string Tpz { get; set; }

        [JsonProperty("htmlz")]
        public string Htmlz { get; set; }

        [JsonProperty("lit")]
        public string Lit { get; set; }

        [JsonProperty("lrx")]
        public string Lrx { get; set; }

        [JsonProperty("zero")]
        public string Zero { get; set; }

        [JsonProperty("bmp")]
        public string Bmp { get; set; }

        [JsonProperty("svg")]
        public string Svg { get; set; }

        [JsonProperty("lrf")]
        public string Lrf { get; set; }

        [JsonProperty("png")]
        public string Png { get; set; }

        [JsonProperty("rtf")]
        public string Rtf { get; set; }

        [JsonProperty("jpeg")]
        public string Jpeg { get; set; }

        [JsonProperty("azw2")]
        public string Azw2 { get; set; }

        [JsonProperty("zip")]
        public string Zip { get; set; }

        [JsonProperty("djv")]
        public string Djv { get; set; }

        [JsonProperty("default")]
        public string Default { get; set; }

        [JsonProperty("cbz")]
        public string Cbz { get; set; }

        [JsonProperty("xps")]
        public string Xps { get; set; }

        [JsonProperty("pobi")]
        public string Pobi { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("rar")]
        public string Rar { get; set; }

        [JsonProperty("jpg")]
        public string Jpg { get; set; }

        [JsonProperty("xhtm")]
        public string Xhtm { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("azw1")]
        public string Azw1 { get; set; }

        [JsonProperty("docx")]
        public string Docx { get; set; }

        [JsonProperty("azw3")]
        public string Azw3 { get; set; }

        [JsonProperty("azw4")]
        public string Azw4 { get; set; }

        [JsonProperty("cbr")]
        public string Cbr { get; set; }

        [JsonProperty("prc")]
        public string Prc { get; set; }

        [JsonProperty("snb")]
        public string Snb { get; set; }

        [JsonProperty("djvu")]
        public string Djvu { get; set; }

        [JsonProperty("tan")]
        public string Tan { get; set; }

        [JsonProperty("odt")]
        public string Odt { get; set; }

        [JsonProperty("mbp")]
        public string Mbp { get; set; }

        [JsonProperty("oxps")]
        public string Oxps { get; set; }

        [JsonProperty("htm")]
        public string Htm { get; set; }

        [JsonProperty("txt")]
        public string Txt { get; set; }
    }

    public partial class CalibreUpdate
    {
        public static CalibreUpdate FromJson(string json) => JsonConvert.DeserializeObject<CalibreUpdate>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CalibreUpdate self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
